name: Git Commands
on: [push, workflow_dispatch]
jobs:
  run-git-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Init Empty Local Clone
        run: git init
        # hint: Using 'master' as the name for the initial branch. This default branch name
        # hint: is subject to change. To configure the initial branch name to use in all
        # hint: of your new repositories, which will suppress this warning, call:
        # hint: 
        # hint: 	git config --global init.defaultBranch <name>
        # hint: 
        # hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
        # hint: 'development'. The just-created branch can be renamed via this command:
        # hint: 
        # hint: 	git branch -m <name>
        # Initialized empty Git repository in /home/runner/work/github-actions-test/github-actions-test/.git/        
      - name: Create Origin Remote
        run: |
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git remote -vv
        # origin	***github.com/xtechware/github-actions-test.git (fetch)
        # origin	***github.com/xtechware/github-actions-test.git (push)
      - name: Pull Origin Remote Main
        # remember to push you will need git config --global user.email and user.name
        run: |
          git fetch --all
          git checkout -b main --track origin/main
          git pull
          ls -al
        # From https://github.com/xtechware/github-actions-test
        #  * [new branch]      main       -> origin/main
        # Switched to a new branch 'main'
        # branch 'main' set up to track 'origin/main'.
        # Already up to date.
        # total 20
        # drwxr-xr-x 4 runner docker 4096 Dec  9 20:31 .
        # drwxr-xr-x 3 runner docker 4096 Dec  9 20:31 ..
        # drwxr-xr-x 8 runner docker 4096 Dec  9 20:31 .git
        # drwxr-xr-x 3 runner docker 4096 Dec  9 20:31 .github
        # -rw-r--r-- 1 runner docker   21 Dec  9 20:31 README.md          
    